server.port=8081

# MySQL datasource (Docker)
#spring.datasource.url=jdbc:mysql://db:3306/securecoda?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

spring.datasource.url=jdbc:mysql://localhost:3306/securecoda?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=#####
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Flyway
spring.flyway.enabled=false

securecoda.poller.enabled=false

poller.interval.ms=60000

coda.api.token=###############
coda.base-url=https://coda.io/apis/v1
